
name: Build and deploy ASP.Net Core app to Azure Web App - CarniExpress-back

on:
  push:
    branches:
      - releace
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore ./CarniExpress-back/CarniExpress-back.csproj

      - name: Build with dotnet
        run: dotnet build ./CarniExpress-back/CarniExpress-back.csproj --configuration Release --no-restore

      - name: Publish application
        run: dotnet publish ./CarniExpress-back/CarniExpress-back.csproj --configuration Release --output ./publish

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: windows-latest
    needs: build

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_64F39E17120E46BE89694764991E0BE8 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_47A57D3C38EA404092DACE9308DFB118 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_B3F0C726A7704D29965E7E43DC5AB31D }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'CarniExpress-back'
          slot-name: 'Production'
          package: ./publish
